name: Rust

on:
  release:
    types:
      - published

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-x86:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: log_viewer-linux-x86
        path: target/release/log_viewer
        error: Failed to produce artifact
        if-no-files-found: error    
        archive: false
      
  build-linux-arm:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: log_viewer-linux-arm
        path: target/release/log_viewer
        error: Failed to produce artifact
        if-no-files-found: error    
        archive: false
  
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: log_viewer-windows
        path: target/release/log_viewer
        error: Failed to produce artifact
        if-no-files-found: error    
        archive: false
      
      
  
  build-macos-arm:
  
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: log_viewer-macos-arm
        path: target/release/log_viewer
        error: Failed to produce artifact
        if-no-files-found: error    
        archive: false
      
  build-macos-x86:
  
    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: log_viewer-macos-x86
        path: target/release/log_viewer
        error: Failed to produce artifact
        if-no-files-found: error    
        archive: false

    
